package engine

import (
	"encoding/json"
	"math"
	"math/big"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/KiritakeKumi/OKEGuiDX/internal/model"
)

// statusFixture is generated by running the original C# StatusUpdate.FillValues
// (see testdata/gen/Gen.cs). Expectations are therefore recorded behaviour, not
// a re-reading of the source.
type statusFixture struct {
	Note  string `json:"note"`
	Cases []struct {
		Name  string `json:"name"`
		Steps []struct {
			In struct {
				Percent     *float64 `json:"percent"`
				EstTotalMS  *float64 `json:"est_total_ms"`
				FramesDone  *int64   `json:"frames_done"`
				FramesTotal *int64   `json:"frames_total"`
				CurrentSize *int64   `json:"current_size"`
				TotalSize   *int64   `json:"total_size"`
				ClipPosMS   *float64 `json:"clip_pos_ms"`
				ClipLenMS   *float64 `json:"clip_len_ms"`
				ElapsedMS   float64  `json:"elapsed_ms"`
			} `json:"in"`
			Want struct {
				Percent      float64  `json:"percent"`
				PercentKnown bool     `json:"percent_known"`
				Speed        string   `json:"speed"`
				ETAKnown     bool     `json:"eta_known"`
				ETAMS        float64  `json:"eta_ms"`
				FramesDone   *int64   `json:"frames_done"`
				FramesTotal  *int64   `json:"frames_total"`
				CurrentSize  *int64   `json:"current_size"`
				Projected    *int64   `json:"projected_size"`
				ClipPosMS    *float64 `json:"clip_pos_ms"`
			} `json:"want"`
		} `json:"steps"`
	} `json:"cases"`
	TimeRemain []struct {
		MS   float64 `json:"ms"`
		Want string  `json:"want"`
	} `json:"time_remain"`
	PercentFormat []struct {
		Percent float64 `json:"percent"`
		Want    string  `json:"want"`
	} `json:"percent_format"`
}

func loadStatusFixture(t *testing.T) statusFixture {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "status_fixture.json"))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var f statusFixture
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	if len(f.Cases) == 0 {
		t.Fatal("fixture has no cases")
	}
	return f
}

func TestStatusUpdateMatchesCSharpFixture(t *testing.T) {
	t.Parallel()
	f := loadStatusFixture(t)
	id := model.NewTaskID()

	for _, tc := range f.Cases {
		t.Run(tc.Name, func(t *testing.T) {
			t.Parallel()
			u := NewStatusUpdate(id, tc.Name)
			for i, step := range tc.Steps {
				applyStep(u, step.In.Percent, step.In.EstTotalMS, step.In.FramesDone,
					step.In.FramesTotal, step.In.CurrentSize, step.In.TotalSize,
					step.In.ClipPosMS, step.In.ClipLenMS, step.In.ElapsedMS)
				u.Fill()

				if got, known := u.Percent(); known != step.Want.PercentKnown {
					t.Errorf("step %d: percent known = %v, want %v", i, known, step.Want.PercentKnown)
				} else if known && math.Abs(got-step.Want.Percent) > 1e-6 {
					t.Errorf("step %d: percent = %v, want %v", i, got, step.Want.Percent)
				}

				if got := u.Speed(); got != step.Want.Speed {
					t.Errorf("step %d: speed = %q, want %q", i, got, step.Want.Speed)
				}

				gotETA, known := u.EstimatedTime()
				if known != step.Want.ETAKnown {
					t.Errorf("step %d: eta known = %v, want %v", i, known, step.Want.ETAKnown)
				} else if known {
					want := ticksFromMS(step.Want.ETAMS)
					if gotETA != want {
						t.Errorf("step %d: eta = %v (%d ticks), want %v (%d ticks)",
							i, gotETA, gotETA/tick, want, want/tick)
					}
				} else if gotETA != UnknownTimeRemain {
					t.Errorf("step %d: unknown eta = %v, want the 30-day sentinel", i, gotETA)
				}

				checkOptionalInt(t, i, "frames done", u.FramesDone, step.Want.FramesDone)
				checkOptionalInt(t, i, "frames total", u.FramesTotal, step.Want.FramesTotal)
				checkOptionalInt(t, i, "current size", u.CurrentSize, step.Want.CurrentSize)
				checkOptionalInt(t, i, "projected size", u.ProjectedSize, step.Want.Projected)

				gotPos, posKnown := u.ClipPosition()
				if (step.Want.ClipPosMS != nil) != posKnown {
					t.Errorf("step %d: clip position known = %v, want %v", i, posKnown, step.Want.ClipPosMS != nil)
				} else if posKnown && gotPos != ticksFromMS(*step.Want.ClipPosMS) {
					t.Errorf("step %d: clip position = %v, want %v", i, gotPos, ticksFromMS(*step.Want.ClipPosMS))
				}
			}
		})
	}
}

// applyStep feeds one observation into the accumulator, skipping the fields the
// fixture left unset, which is what "the step did not report it" means.
func applyStep(u *StatusUpdate, percent, estMS *float64, framesDone, framesTotal, currentSize, totalSize *int64,
	clipPosMS, clipLenMS *float64, elapsedMS float64,
) {
	if percent != nil {
		u.SetPercent(*percent)
	}
	if estMS != nil {
		u.SetEstimatedTime(ticksFromMS(*estMS))
	}
	if framesDone != nil {
		u.SetFramesDone(*framesDone)
	}
	if framesTotal != nil {
		u.SetFramesTotal(*framesTotal)
	}
	if currentSize != nil {
		u.SetCurrentSize(*currentSize)
	}
	if totalSize != nil {
		u.SetProjectedSize(*totalSize)
	}
	if clipPosMS != nil {
		u.SetClipPosition(ticksFromMS(*clipPosMS))
	}
	if clipLenMS != nil {
		u.SetClipLength(ticksFromMS(*clipLenMS))
	}
	u.SetElapsed(ticksFromMS(elapsedMS))
}

// ticksFromMS converts the fixture's millisecond values to the 100 ns ticks the
// legacy TimeSpan used.
func ticksFromMS(ms float64) time.Duration {
	return time.Duration(math.Round(ms*1e4)) * tick
}

func checkOptionalInt(t *testing.T, step int, name string, got func() (int64, bool), want *int64) {
	t.Helper()
	v, ok := got()
	if (want != nil) != ok {
		t.Errorf("step %d: %s known = %v, want %v", step, name, ok, want != nil)
		return
	}
	if ok && v != *want {
		t.Errorf("step %d: %s = %d, want %d", step, name, v, *want)
	}
}

func TestFormatTimeRemainMatchesCSharp(t *testing.T) {
	t.Parallel()
	f := loadStatusFixture(t)
	for _, tc := range f.TimeRemain {
		t.Run(tc.Want, func(t *testing.T) {
			t.Parallel()
			if got := FormatTimeRemain(ticksFromMS(tc.MS)); got != tc.Want {
				t.Errorf("FormatTimeRemain(%v ms) = %q, want %q", tc.MS, got, tc.Want)
			}
		})
	}
}

func TestFormatTimeRemainBoundaries(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name string
		d    time.Duration
		want string
	}{
		{"zero", 0, "0:00:00"},
		{"one second", time.Second, "0:00:01"},
		{"one minute", time.Minute, "0:01:00"},
		{"59 minutes", 59 * time.Minute, "0:59:00"},
		{"one hour", time.Hour, "1:00:00"},
		{"just over one hour", time.Hour + time.Second, "1:00:01"},
		{"25 hours", 25*time.Hour + 30*time.Minute, "25:30:00"},
		{"100 hours", 100*time.Hour + 45*time.Minute, "100:45:00"},
		{"exactly one week", 7 * 24 * time.Hour, "168:00:00"},
		{"one tick past a week", 7*24*time.Hour + tick, "大于一周"},
		{"unknown sentinel", UnknownTimeRemain, "大于一周"},
		{"negative", -90 * time.Minute, "-1:30:00"},
		{"negative sub-second", -1500 * time.Millisecond, "0:00:01"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := FormatTimeRemain(tc.d); got != tc.want {
				t.Errorf("FormatTimeRemain(%v) = %q, want %q", tc.d, got, tc.want)
			}
		})
	}
}

func TestFormatPercentMatchesCSharp(t *testing.T) {
	t.Parallel()
	f := loadStatusFixture(t)
	for _, tc := range f.PercentFormat {
		name := tc.Want
		if name == "" {
			name = "unknown"
		}
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			got, unknown := FormatPercent(tc.Percent)
			if got != tc.Want {
				t.Errorf("FormatPercent(%v) = %q, want %q", tc.Percent, got, tc.Want)
			}
			if unknown != (tc.Percent < 0) {
				t.Errorf("FormatPercent(%v) unknown = %v, want %v", tc.Percent, unknown, tc.Percent < 0)
			}
		})
	}
}

// TestStatusUpdatePriority pins the five-source priority order directly, so a
// reordering regression fails with a readable name instead of a fixture diff.
func TestStatusUpdatePriority(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name string
		set  func(*StatusUpdate)
		want float64
	}{
		{
			name: "percent wins over every other source",
			set: func(u *StatusUpdate) {
				u.SetPercent(90)
				u.SetEstimatedTime(time.Hour)
				u.SetFramesDone(10)
				u.SetFramesTotal(1000)
				u.SetCurrentSize(10)
				u.SetProjectedSize(1000)
				u.SetClipPosition(time.Minute)
				u.SetClipLength(time.Hour)
			},
			want: 90,
		},
		{
			name: "estimated time wins over frames",
			set: func(u *StatusUpdate) {
				u.SetEstimatedTime(100 * time.Second)
				u.SetFramesDone(10)
				u.SetFramesTotal(1000)
				u.SetCurrentSize(10)
				u.SetProjectedSize(1000)
				u.SetClipPosition(time.Minute)
				u.SetClipLength(time.Hour)
			},
			want: 10,
		},
		{
			name: "frames win over sizes",
			set: func(u *StatusUpdate) {
				u.SetFramesDone(500)
				u.SetFramesTotal(1000)
				u.SetCurrentSize(10)
				u.SetProjectedSize(1000)
				u.SetClipPosition(time.Minute)
				u.SetClipLength(time.Hour)
			},
			want: 50,
		},
		{
			name: "sizes win over clip position",
			set: func(u *StatusUpdate) {
				// Integer division, as in the legacy ulong expression: the
				// sizes source here yields 100%, the clip source 25%.
				u.SetCurrentSize(1000)
				u.SetProjectedSize(1000)
				u.SetClipPosition(15 * time.Minute)
				u.SetClipLength(time.Hour)
			},
			want: 100,
		},
		{
			name: "clip position is the last resort",
			set: func(u *StatusUpdate) {
				u.SetClipPosition(15 * time.Minute)
				u.SetClipLength(time.Hour)
			},
			want: 25,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			u := NewStatusUpdate(model.NewTaskID(), "x265")
			u.SetElapsed(10 * time.Second)
			tc.set(u)
			u.Fill()
			got, known := u.Percent()
			if !known {
				t.Fatal("percent is unknown, want a value")
			}
			if math.Abs(got-tc.want) > 1e-9 {
				t.Errorf("percent = %v, want %v", got, tc.want)
			}
		})
	}
}

// TestStatusUpdateZeroGuards covers the divisions the legacy code let throw and
// swallow; the port has to skip the same work instead of producing Inf/NaN.
func TestStatusUpdateZeroGuards(t *testing.T) {
	t.Parallel()
	t.Run("zero frame total falls through", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "x265")
		u.SetFramesDone(50)
		u.SetFramesTotal(0)
		u.SetClipPosition(15 * time.Minute)
		u.SetClipLength(time.Hour)
		u.Fill()
		got, known := u.Percent()
		if !known || math.Abs(got-25) > 1e-9 {
			t.Errorf("percent = %v (known %v), want 25", got, known)
		}
	})

	t.Run("zero size total falls through", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "mkvmerge")
		u.SetCurrentSize(1)
		u.SetProjectedSize(0)
		u.SetClipPosition(30 * time.Second)
		u.SetClipLength(2 * time.Minute)
		u.Fill()
		got, known := u.Percent()
		if !known || math.Abs(got-25) > 1e-9 {
			t.Errorf("percent = %v (known %v), want 25", got, known)
		}
	})

	t.Run("zero clip length is not a fraction source", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "vspipe")
		u.SetClipPosition(30 * time.Second)
		u.SetClipLength(0)
		u.Fill()
		if _, known := u.Percent(); known {
			t.Error("percent is known, want unknown")
		}
		if _, known := u.EstimatedTime(); known {
			t.Error("eta is known, want unknown")
		}
	})

	t.Run("zero fraction never divides", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "x265")
		u.SetPercent(0)
		u.SetElapsed(10 * time.Second)
		u.Fill()
		if got, known := u.EstimatedTime(); known || got != UnknownTimeRemain {
			t.Errorf("eta = %v (known %v), want the unknown sentinel", got, known)
		}
		if got := u.Speed(); got != "" {
			t.Errorf("speed = %q, want empty", got)
		}
	})

	t.Run("zero elapsed yields no speed", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "x265")
		u.SetFramesDone(50)
		u.SetFramesTotal(100)
		u.Fill()
		if got := u.Speed(); got != "" {
			t.Errorf("speed = %q, want empty", got)
		}
		if got, known := u.EstimatedTime(); !known || got != 0 {
			t.Errorf("eta = %v (known %v), want 0", got, known)
		}
	})

	t.Run("fraction zero with current size skips derivation", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "mkvmerge")
		u.SetPercent(0)
		u.SetCurrentSize(100)
		u.Fill()
		if _, known := u.ProjectedSize(); known {
			t.Error("projected size is known, want unknown (division by zero)")
		}
		if got, known := u.EstimatedTime(); known || got != UnknownTimeRemain {
			t.Errorf("eta = %v (known %v), want the unknown sentinel", got, known)
		}
	})
}

// TestStatusUpdateBackDerivation covers the three "counter missing" paths and
// their truncation, which is where an off-by-one would be invisible in normal
// use but wrong in the UI.
func TestStatusUpdateBackDerivation(t *testing.T) {
	t.Parallel()
	t.Run("frames done truncates", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "x265")
		u.SetFramesTotal(1000)
		u.SetPercent(33.3)
		u.Fill()
		got, known := u.FramesDone()
		if !known || got != 333 {
			t.Errorf("frames done = %d (known %v), want 333", got, known)
		}
	})

	t.Run("frames total truncates", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "x265")
		u.SetFramesDone(1)
		u.SetPercent(33.3)
		u.Fill()
		got, known := u.FramesTotal()
		if !known || got != 3 {
			t.Errorf("frames total = %d (known %v), want 3", got, known)
		}
	})

	t.Run("projected size truncates", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "mkvmerge")
		u.SetCurrentSize(999)
		u.SetPercent(33.3)
		u.Fill()
		got, known := u.ProjectedSize()
		if !known || got != 3000 {
			t.Errorf("projected size = %d (known %v), want 3000", got, known)
		}
	})

	t.Run("clip position truncates", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "vspipe")
		u.SetClipLength(time.Second)
		u.SetPercent(33.3)
		u.Fill()
		got, known := u.ClipPosition()
		if !known || got != 333*time.Millisecond {
			t.Errorf("clip position = %v (known %v), want 333ms", got, known)
		}
	})

	t.Run("reported values are never overwritten", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "x265")
		u.SetFramesDone(7)
		u.SetFramesTotal(100)
		u.SetCurrentSize(5)
		u.SetProjectedSize(1000)
		u.SetPercent(25)
		u.Fill()
		if got, _ := u.FramesDone(); got != 7 {
			t.Errorf("frames done = %d, want the reported 7", got)
		}
		if got, _ := u.FramesTotal(); got != 100 {
			t.Errorf("frames total = %d, want the reported 100", got)
		}
		if got, _ := u.CurrentSize(); got != 5 {
			t.Errorf("current size = %d, want the reported 5", got)
		}
		if got, _ := u.ProjectedSize(); got != 1000 {
			t.Errorf("projected size = %d, want the reported 1000", got)
		}
	})
}

// TestStatusUpdateETAFallback covers the branch taken when the sliding window
// cannot be used: fewer than ten samples, stalled progress, or sub-five-second
// spacing. The expectation is elapsed * (1/fraction - 1).
func TestStatusUpdateETAFallback(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name    string
		elapsed time.Duration
		percent float64
		want    time.Duration
	}{
		{"quarter done", 10 * time.Second, 25, 30 * time.Second},
		{"half done", 10 * time.Second, 50, 10 * time.Second},
		{"tenth done", 10 * time.Second, 10, 90 * time.Second},
		{"complete", 10 * time.Second, 100, 0},
		{"negative estimate when past 100", 9 * time.Second, 150, -3 * time.Second},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			u := NewStatusUpdate(model.NewTaskID(), "x265")
			u.SetPercent(tc.percent)
			u.SetElapsed(tc.elapsed)
			u.Fill()
			got, known := u.EstimatedTime()
			if !known {
				t.Fatalf("eta is unknown, want %v", tc.want)
			}
			if got != tc.want {
				t.Errorf("eta = %v, want %v", got, tc.want)
			}
		})
	}
}

// TestStatusUpdateETAWindow covers the sliding-window branch: with samples at
// least five seconds apart and progress since the sample ten observations ago,
// the estimate is (elapsed - sampled elapsed) * (1 - fraction) / delta.
func TestStatusUpdateETAWindow(t *testing.T) {
	t.Parallel()
	t.Run("progress since slot zero uses the window", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "x265")
		// Ten samples at 10% per 6 s.
		for i := 1; i <= 10; i++ {
			u.SetFramesDone(int64(i * 100))
			u.SetFramesTotal(1000)
			u.SetElapsed(time.Duration(i*6) * time.Second)
			u.Fill()
		}
		// Slot 0 holds elapsed=6s, fraction=0.1. The eleventh sample jumps to
		// 15%: (66-6)s * 0.85 / 0.05 = 1020 s, which is the value the C#
		// fixture records for window_wrap_progress.
		u.SetFramesDone(150)
		u.SetElapsed(66 * time.Second)
		u.Fill()
		got, known := u.EstimatedTime()
		if !known || got != 1020*time.Second {
			t.Errorf("eta = %v (known %v), want 1020s", got, known)
		}
	})

	t.Run("stalled progress falls back to the whole elapsed time", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "x265")
		for i := 1; i <= 11; i++ {
			u.SetFramesDone(500)
			u.SetFramesTotal(1000)
			u.SetElapsed(time.Duration(i*10) * time.Second)
			u.Fill()
		}
		got, known := u.EstimatedTime()
		if !known || got != 110*time.Second {
			t.Errorf("eta = %v (known %v), want 110s", got, known)
		}
	})

	t.Run("sub-five-second spacing falls back", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "x265")
		u.SetFramesDone(100)
		u.SetFramesTotal(1000)
		u.SetElapsed(3 * time.Second)
		u.Fill()
		u.SetFramesDone(200)
		u.SetElapsed(6 * time.Second)
		u.Fill()
		got, known := u.EstimatedTime()
		if !known || got != 24*time.Second {
			t.Errorf("eta = %v (known %v), want 24s", got, known)
		}
	})

	t.Run("fewer than ten samples use the fallback", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "x265")
		for i := 1; i <= 3; i++ {
			u.SetFramesDone(int64(i * 100))
			u.SetFramesTotal(1000)
			u.SetElapsed(time.Duration(i*10) * time.Second)
			u.Fill()
		}
		got, known := u.EstimatedTime()
		if !known || got != 70*time.Second {
			t.Errorf("eta = %v (known %v), want 70s", got, known)
		}
	})

	t.Run("window wraps after ten samples", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "x265")
		for i := 1; i <= 10; i++ {
			u.SetFramesDone(int64(i * 100))
			u.SetFramesTotal(1000)
			u.SetElapsed(time.Duration(i*6) * time.Second)
			u.Fill()
		}
		// The eleventh sample overwrites slot 0, so the comparison now runs
		// against the sample from six seconds ago (10% -> 50%).
		u.SetFramesDone(500)
		u.SetElapsed(66 * time.Second)
		u.Fill()
		got, known := u.EstimatedTime()
		if !known || got != 75*time.Second {
			t.Errorf("eta = %v (known %v), want 75s", got, known)
		}
	})
}

// TestStatusUpdateStickyValues pins the legacy "swallowed exception" behaviour:
// when the ETA arithmetic fails (zero fraction, zero elapsed, overflow), the
// previously computed value stays in place and the window index does not move.
func TestStatusUpdateStickyValues(t *testing.T) {
	t.Parallel()
	t.Run("eta survives a zero fraction", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "x265")
		u.SetPercent(50)
		u.SetElapsed(10 * time.Second)
		u.Fill()
		if got, known := u.EstimatedTime(); !known || got != 10*time.Second {
			t.Fatalf("eta = %v (known %v), want 10s", got, known)
		}
		u.SetPercent(0)
		u.Fill()
		if got, known := u.EstimatedTime(); !known || got != 10*time.Second {
			t.Errorf("eta after zero fraction = %v (known %v), want the sticky 10s", got, known)
		}
	})

	t.Run("projected size survives a zero fraction", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(model.NewTaskID(), "mkvmerge")
		u.SetCurrentSize(100)
		u.SetPercent(50)
		u.Fill()
		if got, known := u.ProjectedSize(); !known || got != 200 {
			t.Fatalf("projected size = %d (known %v), want 200", got, known)
		}
		u.SetPercent(0)
		u.Fill()
		if got, known := u.ProjectedSize(); !known || got != 200 {
			t.Errorf("projected size after zero fraction = %d (known %v), want the sticky 200", got, known)
		}
	})
}

func TestStatusUpdateEvent(t *testing.T) {
	t.Parallel()
	id := model.NewTaskID()

	t.Run("unknown values map to the model's sentinels", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(id, "vspipe")
		ev := u.Event()
		if ev.TaskID != id {
			t.Errorf("TaskID = %v, want %v", ev.TaskID, id)
		}
		if ev.Progress != model.TaskRunning {
			t.Errorf("Progress = %v, want RUNNING", ev.Progress)
		}
		if ev.Step != "vspipe" {
			t.Errorf("Step = %q, want %q", ev.Step, "vspipe")
		}
		if ev.Percent != -1 {
			t.Errorf("Percent = %v, want -1", ev.Percent)
		}
		if ev.TimeRemainSeconds != UnknownTimeRemain.Seconds() {
			t.Errorf("TimeRemainSeconds = %v, want the 30-day sentinel", ev.TimeRemainSeconds)
		}
	})

	t.Run("derived values are carried through", func(t *testing.T) {
		t.Parallel()
		u := NewStatusUpdate(id, "x265")
		u.SetFramesDone(50)
		u.SetFramesTotal(200)
		u.SetElapsed(10 * time.Second)
		u.SetBitRate("1234.56 kb/s")
		u.Fill()

		ev := u.Event()
		if ev.Percent != 25 {
			t.Errorf("Percent = %v, want 25", ev.Percent)
		}
		if ev.Speed != "5 FPS" {
			t.Errorf("Speed = %q, want %q", ev.Speed, "5 FPS")
		}
		if ev.BitRate != "1234.56 kb/s" {
			t.Errorf("BitRate = %q, want %q", ev.BitRate, "1234.56 kb/s")
		}
		if ev.FramesDone != 50 || ev.FramesTotal != 200 {
			t.Errorf("frames = %d/%d, want 50/200", ev.FramesDone, ev.FramesTotal)
		}
		if ev.TimeRemainSeconds != 30 {
			t.Errorf("TimeRemainSeconds = %v, want 30", ev.TimeRemainSeconds)
		}
	})
}

// TestStatusUpdatePercentUnknown covers the model's "negative means unknown"
// convention on the input side.
func TestStatusUpdatePercentUnknown(t *testing.T) {
	t.Parallel()
	u := NewStatusUpdate(model.NewTaskID(), "x265")
	u.SetPercent(-1)
	if _, known := u.Percent(); known {
		t.Error("percent is known after SetPercent(-1), want unknown")
	}
	// A negative percent must not poison the other sources.
	u.SetFramesDone(50)
	u.SetFramesTotal(100)
	u.Fill()
	if got, known := u.Percent(); !known || got != 50 {
		t.Errorf("percent = %v (known %v), want 50", got, known)
	}
}

func TestFormatTimeRemainUnknownSentinel(t *testing.T) {
	t.Parallel()
	if got := FormatTimeRemain(UnknownTimeRemain); got != "大于一周" {
		t.Errorf("FormatTimeRemain(UnknownTimeRemain) = %q, want %q", got, "大于一周")
	}
}

func TestFormatPercentNaN(t *testing.T) {
	t.Parallel()
	if got, unknown := FormatPercent(math.NaN()); got != "NaN%" || unknown {
		t.Errorf("FormatPercent(NaN) = (%q, %v), want (%q, false)", got, unknown, "NaN%")
	}
}

// TestTruncateCount pins the legacy (ulong) cast semantics discovered by running
// the original code: the value is truncated towards zero first, and only the
// truncated result is range-checked.
func TestTruncateCount(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name string
		num  int64
		den  int64
		want int64
		ok   bool
	}{
		{"positive truncates", 3333, 10, 333, true},
		{"negative fraction truncates to zero", -25, 100, 0, true},
		{"negative below minus one overflows", -150, 100, 0, false},
		{"exact", 42, 1, 42, true},
		{"zero", 0, 7, 0, true},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got, ok := truncateCount(big.NewRat(tc.num, tc.den))
			if ok != tc.ok || (ok && got != tc.want) {
				t.Errorf("truncateCount(%d/%d) = (%d, %v), want (%d, %v)",
					tc.num, tc.den, got, ok, tc.want, tc.ok)
			}
		})
	}
}

// TestSetPercentNegativeIsUnknown documents an intentional deviation: the C#
// decimal property accepted a negative percentage and propagated it, while
// model.StatusEvent defines a negative percent as "unknown". The Go setter
// therefore clears the source instead of poisoning the derivation.
func TestSetPercentNegativeIsUnknown(t *testing.T) {
	t.Parallel()
	u := NewStatusUpdate(model.NewTaskID(), "x265")
	u.SetPercent(-50)
	u.SetFramesTotal(100)
	u.Fill()
	if _, known := u.Percent(); known {
		t.Error("percent is known after SetPercent(-50), want unknown")
	}
	if _, known := u.FramesDone(); known {
		t.Error("frames done is known, want unknown (the legacy cast overflowed)")
	}
}
